# Site settings
title: Kandyce Houston
email: kandyceburks@gmail.com
description: Senior SWE | AI/ML Grad Student
baseurl: ""
url: ""
author: Kandyce Houston

icon: fa-joomla # Font Awesome class for your site's icon

# Social settings
github_url: https://github.com/kandycehouston
linkedin_url: https://www.linkedin.com/in/kandyceburks/

# Build settings
markdown: kramdown

sass:
style: compressed

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag